name: Triggers
run-name: Triggers
on:
  push:
    branches:
      - aprendiendo-github-actions
  pull_request:
    branches:
      - aprendiendo-github-actions
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created, edited, deleted]
  schedule:
    - cron: '50 * * * *'

jobs:
  Triggers_Push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Triggered by
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Show OS and branch
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Show branch and repository
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  Triggers_Pull_Request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Triggered by
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Show OS and branch
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Show branch and repository
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  Triggers_Issues:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Triggered by
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Show OS and branch
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Show branch and repository
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  Triggers_Issue_Comment:
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Triggered by
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Show OS and branch
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Show branch and repository
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  Triggers_Schedule:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Triggered by
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Show OS and branch
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Show branch and repository
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Show execution time
        run: echo "â° The time is now ${{ github.event.schedule }}."
